export default {
  light: {
    background: '#ffffff',
    backgroundSecondary: '#f0f0ff',
    backgroundCard: '#f8f8ff',
    backgroundComments: '#ffffff',
    text: '#111',
    textSecondary: '#555',
    textOnPrimary: '#fff',
    border: '#ccc',
    primary: '#6e56cf',
    primaryDark: '#483887',
    textMaps: '#eeeeee',
    primaryLight: '#b9b6ff',
    error: '#e63946',
    backgroundPhotos: '#f2f2f5',
    gradients: ['#ffffff', '#f0f0ff', '#e9e6ff'] as const,
  },
  dark: {
    background: '#1e1630',
    backgroundSecondary: '#1b0033',
    backgroundCard: '#1f1f25',
    backgroundComments: '#1c1c1e',
    text: '#fefefe',
    textSecondary: '#aaa',
    textMaps: '#eeeeee',
    textOnPrimary: '#fff',
    border: '#555',
    primary: '#b18aff',
    primaryDark: '#483887',
    primaryLight: '#6e56cf',
    error: '#f44336',
    backgroundPhotos: '#2d2442',
    gradients: ['#0b0b0f', '#1b0033', '#3e1d73'] as const,
  },
};
