services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/traefik.toml:ro
      - ./traefik/traefik_dynamic.toml:/traefik_dynamic.toml:ro
      - ./traefik/acme.json:/acme.json
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/portainer/data:/data
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.portainer.rule=Host(`portainer.planejeja.com.br`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=lets-encrypt"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  minha-app:
    image: minha-nextjs-app:latest
    container_name: minha-nextjs-app
    restart: always
    networks:
      - web
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.minhaapp.rule=Host(`planejeja.com.br`)"
      - "traefik.http.routers.minhaapp.entrypoints=websecure"
      - "traefik.http.routers.minhaapp.tls=true"
      - "traefik.http.routers.minhaapp.tls.certresolver=lets-encrypt"
      - "traefik.http.services.minhaapp.loadbalancer.server.port=3000"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  event-link:
    build:
      context: ./event-link
    container_name: event-link
    restart: unless-stopped
    networks:
      - web

    # ✅ definitivo: edita no VSCode + scp e pronto
    volumes:
      - /root/app-planejeja/static-link:/usr/share/nginx/html:ro

    # ✅ opcional/recomendado: container mais travado
    read_only: true
    tmpfs:
      - /tmp

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"

      # ✅ rota só para arquivos do link/convite
      - "traefik.http.routers.eventlink.rule=Host(`planejeja.com.br`) && (Path(`/app.html`) || Path(`/logo.png`) || PathPrefix(`/download`))"
      - "traefik.http.routers.eventlink.entrypoints=websecure"
      - "traefik.http.routers.eventlink.tls=true"
      - "traefik.http.routers.eventlink.tls.certresolver=lets-encrypt"
      - "traefik.http.services.eventlink.loadbalancer.server.port=80"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  web:
    external: true
